version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-27-alpha

    steps:
    - run:
        name: Install Build Tools
        # Otherwise circle ci shows some accepting licence problem
        command: echo y | sdkmanager "build-tools;27.0.3"
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_artifacts:
        path: app/build/outputs
        destination: outputs
